language: python
services:
  - docker

before_install:
  - touch deploy.rsa
  - openssl aes-256-cbc -K $encrypted_64cbeea805df_key -iv $encrypted_64cbeea805df_iv
    -in deploy.rsa.enc -out deploy.rsa -d
  - echo $docker_hub_gemma_pw | docker login -u $docker_hub_gemma --password-stdin
  - docker build -t gemmawu/sasharingapp:1.0 .

# install:

# before_script:

# script:

after_success:
  - chmod 600 deploy.rsa
  - eval $(ssh-agent)
  - ssh-add deploy.rsa
  - "./deploy.sh"

# deploy:

after_deploy:
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - docker-compose -f docker-compose-total.yml -p mongodb up -d && bash setup.sh
