language: generic
services:
  - docker

before_install:
  - touch deploy.rsa
  - openssl aes-256-cbc -K $encrypted_64cbeea805df_key -iv $encrypted_64cbeea805df_iv
    -in deploy.rsa.enc -out deploy.rsa -d
  - echo $docker_hub_gemma_pw | docker login -u $docker_hub_gemma --password-stdin
  - docker build -t gemmawu/sasharingapp:1.0 ./app
  - docker tag gemmawu/sasharingapp:1.0 gemmawu/sasharingapp:1.0
  - docker push gemmawu/sasharingapp:1.0 | grep 'Layer already exist' &> /dev/null

# install:

# before_script:

# script:

after_success:
  - "./deploy.sh"

# deploy:

# after_deploy:
