language: python
services:
- docker
before_install:
- echo $docker_hub_gemma_pw | docker login -u $docker_hub_gemma --password-stdin
- docker build -t gemmawu/sasharingapp:1.0 .
- touch ~\/.ssh/deploy.rsa
- openssl aes-256-cbc -K $encrypted_8ac82a6d0901_key -iv $encrypted_8ac82a6d0901_iv
  -in deploy.rsa.enc -out ~\/.ssh/deploy.rsa -d
# install:

# before_script:

# script:

after_success:
- chmod 600 ~\/.ssh/deploy.rsa
- eval $(ssh-agent)
- ssh-add ~\/.ssh/deploy.rsa
- "./deploy.sh"
# before_deploy:

# deploy:

after_deploy:
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker-compose -f docker-compose-total.yml -p mongodb up -d && bash setup.sh
# after_script: 

