version: "3"
services:
  app_data1:
    # image: gemma/mongodb:latest
    image: mongo:4.1.6-xenial
    deploy:
      # replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 27020:27017
    command: mongod --replSet rs
    volumes:
      - .:/src/app/
    depends_on:
      - app_data2
      - app_data3
    networks:
      - webnet
  app_data2:
    # image: gemma/mongodb:latest
    image: mongo:4.1.6-xenial
    deploy:
      # replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 27018:27017
    command: mongod --replSet rs
    networks:
      - webnet
  app_data3:
    # image: gemma/mongodb:latest
    image: mongo:4.1.6-xenial
    deploy:
      # replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure 
    ports:
      - 27019:27017
    command: mongod --replSet rs
    networks:
      - webnet
networks:
  webnet:
