version: "3"
services:
  share-app:
    # replace username/repo:tag with your name and image details
    # image: gemma/sharing-app
    image: gemmawu/sasharingapp:1.0
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    hostname: share-app
    container_name: share-app
    ports:
      - 3000:3000
